operational/membership.md

Fix dead link

---

operational/branding.md

One of the font links was missing a closing tag.
Part of #6

Fix broken link

---

legal/bylaws.md

Good standing exemption due to Foundation membership system failure. 
DO NOT PUBLISH BEFORE November 1, 2020

Vote 1 - add good standing exemption

---

operational/membership.md

Update membership policy to reflect Board vote

---

procedures/New chapter creation

Issues and risks still need to update or remove the template text.

New Chapter Creation

---

procedures/invoicing.md

A process is standard and staff names and email addresses should not be used. If responsibilities are reassigned or staff leaves updates will not be necessary.
I only removed my name Lisa from tasks.

Invoicing Process Update

---

guidebook/chapter-leader.md

Update links to current valid references, and remove spurious whitespace.
Fixes OWASP/www-policy#11.
Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

Tweak Chapter Leaders Guide

---

legal/bylaws.md
operational/board-code-of-conduct.md

Approved by the Board on 1/27/2021

Director Removal and Anti Harrassment

---

operational/signatory2.md

Update signing limits

---

legal/bylaws.md
procedures/evoting.md

Changes the bylaws to permit eVotes, and documents the procedure for eVoting

Explicit evote support

---

operational/policy-changes.md

Small consent policy

---

legal/bylaws.md

Updated March Consent Package - with @kingthorin 's feedback

Updated March Consent Package

---

operational/events.md

Will do a full spelling and grammar check after reviews are in

Draft of no balance events policy

---

operational/membership.md

spelling error corrected

---

operational/donations.md

Only merge this change if the motion is approved. 
See https://owasp.org/www-board/meetings/202107.html for motion

Change derestriction policy

---

operational/election.md

This is a small motion to make the nearest business day the scheduled day, to help with promotion and to avoid weekend duties for staff.

Motion to adopt the next business day

---

operational/chapters.md

The Chapter Handbook is still in draft. This should be changed once the Chapter Handbook is finalized or approved by the Chapter Committee.

Mark chapter handbook is in draft

---

legal/virtual-trainer-agreement.md

Added R to Virtual in title

---

operational/projects.md

This issue resolves #132 where all documentation projects are out of compliance with our own policy. The language provides an organic path to an international standard, and it leaves open the possibility of exceptions which must be approved by the project committee.

Clarifying license expectations

---

operational/committees.md
operational/whistleblower.md

Per the Board's direction to remove the compliance committee from the Committee policy.

Draft removal of compliance committee
